"""
Unit tests for RecursiveSplitter logic.
"""

import pytest
from src.libs.splitter.recursive_splitter import RecursiveSplitter
from src.core.settings import IngestionSettings

@pytest.fixture
def mock_settings():
    """Mock settings for testing RecursiveSplitter."""
    class MockIngestionSettings:
        def __init__(self):
            self.ingestion = self.MockIngestion()

        class MockIngestion:
            chunk_size = 50
            chunk_overlap = 10

    return MockIngestionSettings()

def test_recursive_splitter_merge_logic(mock_settings):
    """
    Test the merge logic of RecursiveSplitter to ensure small chunks are combined correctly.
    """
    splitter = RecursiveSplitter(settings=mock_settings)

    # Simulate chunks generated by the splitter
    chunks = [
        "This is a",
        "small chunk.",
        "Another small",
        "chunk that should",
        "be merged together."
    ]

    # Apply merge logic
    merged_chunks = splitter.merge_chunks(chunks)

    # Assertions
    assert len(merged_chunks) == 1, "Chunks should be merged into one."
    assert merged_chunks[0] == "This is a small chunk. Another small chunk that should be merged together.", "Merged chunk content is incorrect."